name: DevSecOps Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test_pull_request:
    name: Test Pull Request
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v3   # Updated to v3
     - uses: actions/setup-node@v3 # Updated to v3
       with:
         node-version: '14'
     - run: npm ci
     - run: npm test
     - run: npm run build  # Fixed indentation and spacing issue

  
  
  # security_checks:
  #   name: Security Checks
  #   runs-on: ubuntu-latest
  #   steps:
  #   - name: Checkout code
  #     uses: actions/checkout@v3
  #   - name: Setup Node.js
  #     uses: actions/setup-node@v3
  #     with:
  #       node-version: '18'
  #   - name: Install dependencies
  #     run: npm ci
  #   - name: Run npm audit
  #     run: npm audit --audit-level=moderate
  #   - name: Run Snyk to check for vulnerabilities
  #     uses: snyk/actions/node@master
  #     env:
  #       SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

  # code_quality:
  #   name: Code Quality
  #   runs-on: ubuntu-latest
  #   steps:
  #   - name: Checkout code
  #     uses: actions/checkout@v3
  #   - name: Setup Node.js
  #     uses: actions/setup-node@v3
  #     with:
  #       node-version: '18'
  #   - name: Install dependencies
  #     run: npm ci
  #   - name: Run ESLint
  #     run: npx eslint .
  #   - name: Run Prettier
  #     run: npx prettier --check .

  # security_scanning:
  #   name: Security Scanning
  #   runs-on: ubuntu-latest
  #   steps:
  #   - name: Checkout code
  #     uses: actions/checkout@v3
  #   - name: Run OWASP ZAP Scan
  #     uses: zaproxy/action-full-scan@v0.7.0
  #     with:
  #       target: 'https://localhost:3001'  # Ensure your app is running for the scan

  # database_test:
  #   name: Database Connection Test
  #   runs-on: ubuntu-latest
  #   steps:
  #   - name: Checkout code
  #     uses: actions/checkout@v3
  #   - name: Setup Node.js
  #     uses: actions/setup-node@v3
  #     with:
  #       node-version: '18'
  #   - name: Install dependencies
  #     run: npm ci
  #   - name: Run database connection test
  #     run: npm test src/tests/database.test.js
  #     env:
  #       MONGODB_URI: ${{ secrets.MONGODB_URI }}
