name: DevSecOps Security Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  security_checks:
    name: Security Checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci
        working-directory: main-app

      # Run npm audit to check for vulnerabilities with high severity or above
      - name: Run npm audit
        run: npm audit --audit-level=high || echo "Audit completed with known issues"
        working-directory: main-app

      # Run Snyk for additional vulnerability scanning
      - name: Run Snyk vulnerability scan
        uses: snyk/actions/node@master
        with:
          command: test --severity-threshold=high
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        continue-on-error: true  

  code_quality:
    name: Code Quality
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci
        working-directory: main-app

      # Run ESLint for code linting and style checks
      - name: Run ESLint
        run: npx eslint . --fix
        working-directory: main-app

      # Run Prettier for code formatting
      - name: Run Prettier
        run: npx prettier --write .
        working-directory: main-app
