name: DevSecOps Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test_pull_request:
    name: Test Pull Request
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci
        working-directory: main-app

      - name: Run tests
        run: npm test
        working-directory: main-app

  security_checks:
    name: Security Checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci
        working-directory: main-app

      # Run npm audit, ignore errors, and continue the build
      - name: Run npm audit with ignored errors
        run: npm audit --audit-level=high || echo "Audit completed with known issues"
        working-directory: main-app

      # Run Snyk for additional vulnerability checks without failing the build
      - name: Run Snyk vulnerability scan
        uses: snyk/actions/node@master
        with:
          command: test --severity-threshold=high
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        continue-on-error: true  # Allows the job to continue even if vulnerabilities are found

  code_quality:
    name: Code Quality
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci
        working-directory: main-app

      # Run ESLint for JavaScript/TypeScript code style and linting
      - name: Run ESLint
        run: npx eslint . --fix
        working-directory: main-app

      # Run Prettier for code formatting
      - name: Run Prettier
        run: npx prettier --write .
        working-directory: main-app

  database_test:
    name: Database Connection Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci
        working-directory: main-app

      # Run the database test with environment variable for MongoDB URI
      - name: Run database connection test
        run: npm test src/tests/database.test.js
        working-directory: main-app
        env:
          MONGODB_URI: ${{ secrets.MONGODB_URI }}
