name: DevSecOps Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test_pull_request:
    name: Test Pull Request
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci
        working-directory: main-app

      - name: Run tests
        run: npm test
        working-directory: main-app

  security_checks:
    name: Security Checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci
        working-directory: main-app

      - name: Run npm audit for vulnerabilities
        run: npm audit --audit-level=moderate
        working-directory: main-app

      - name: Run Snyk for vulnerability check
        uses: snyk/actions/node@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

  code_quality:
    name: Code Quality
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci
        working-directory: main-app

      - name: Run ESLint
        run: npx eslint . --fix
        working-directory: main-app

      - name: Run Prettier
        run: npx prettier --write .
        working-directory: main-app

  security_checks:
    name: Security Checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci
        working-directory: main-app

      # Run npm audit for vulnerabilities
      - name: Run npm audit
        run: npm audit --audit-level=moderate
        working-directory: main-app

      # Run Snyk for vulnerability check
      - name: Run Snyk vulnerability scan
        uses: snyk/actions/node@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

  database_test:
    name: Database Connection Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci
        working-directory: main-app

      - name: Run database connection test
        run: npm test src/tests/database.test.js
        working-directory: main-app
        env:
          MONGODB_URI: ${{ secrets.MONGODB_URI }}
