name: DevSecOps Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test_pull_request:
    name: Test Pull Request
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v3   # Updated to v3
     - uses: actions/setup-node@v3 # Updated to v3
       with:
         node-version: '14'
     - run: npm ci
     - run: npm test
     - run: npm run build  # Fixed indentation and spacing issue
